name: "Synthesis and Results"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  synth-and-publish:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[gh-bot]') }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Run Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Run Synthesis
        run: |
          echo "Running Synthesis..."
          nix develop --command make synth
          echo "Synthesis complete."

      - name: Run Static Timing Analysis
        run: |
          echo "Running STA..."
          nix develop --command make sta
          echo "STA complete."

      - name: Prepare output directory
        run: |
          mkdir -p out/results
          echo "Created out/results directory."

      - name: Generate Verilog
        run: |
          echo "Generating Verilog..."
          nix develop --command make verilog
          echo "Verilog generation complete."

      - name: Prepare artifacts folder
        run: |
          mkdir -p artifacts
          cp -r out/results artifacts/
          cp -r out/verilog artifacts/
          # Copy netlists from out/synth
          find out/synth -name "*.v" -exec cp {} artifacts/ \;
          # Copy any verilog from generated/ if needed
          if [ -d "generated" ]; then
            find generated -name "*.v" -exec cp {} artifacts/ \;
          fi

      - name: Upload synthesis results
        uses: actions/upload-artifact@v4
        with:
          name: synthesis-results
          path: artifacts
